[project]
name = "ml-ops-part-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "jupyter>=1.1.1",
    "mlflow>=2.22.0",
    "notebook>=7.4.2",
    "pandas>=2.2.3",
    "seaborn>=0.13.2",
    "xgboost>=2.1.4",
]
